name: Deploy to Both Instances via SSH

on:
  push:
    branches: [main]

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Instance 1 (local self-hosted runner)
        run: |
          echo "Starting deployment at:" $(date)
          cd /home/ec2-user/testloadbalancer
          echo "Cleaning up local changes"
          git reset --hard HEAD
          git clean -fd
          echo "Pulling latest changes"
          git pull origin main
          echo "Restarting service"
          sudo systemctl restart testloadbalancer.service
          echo "Finished at:" $(date)

      # - name: Deploy to Instance 2 (remote over SSH)
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.INSTANCE_2_IP }}
      #     username: ec2-user
      #     key: ${{ secrets.KEY_TO_INSTANCE2 }}
      #     script: |
      #       cd /home/ec2-user/testloadbalancer
      
      #       git pull origin main
      #       sudo systemctl restart testloadbal.service